### ISSUE TITLE
SEAC2018 wishlist

### ISSUE THREAD

**Issue by f-silva-archaeo** [f-silva-archaeo/skyscapeR#3]
- [x] update the significance test to SEAC2018 version
- [x] start using Swiss Ephemeris and ARCHAEOCOSMO tools
- [ ] play with curvigram option to split rising and setting data
- [ ] add stellarium remote control feature

**Comment by vreijs** [comment]
Hello Fabio,
Are there additional people interested in writing/testing/etc? Hope
SEAC2018 is going well.
All the best,
Victor
