### ISSUE TITLE
checking astrolib calls

### ISSUE THREAD

**Issue by vreijs** [f-silva-archaeo/skyscapeR#4]
I find the following astrolib calls Does this look ok-ish? 
I also mention the possible swe_functions. Some of the underlying functions from astrolib (ten, precess, co_nutate, co_abberation) are part of the calls from swe, so are perhaps not explicitly needed is skyscapeR.
Some others could be called from ARCHAEOCOSMO (co_refract, precess, hor2eq, hadec2altaz):
```
jd <- astrolibR::jdcnv(2000, 1, 1, 0.)  # J2000.0
This should be: jdcnv(2000, 1, 1, 12.) as J2000.0 = 2451545

See astrolibR.pdf manual: https://cran.r-project.org/web/packages/astrolibR/vignettes/astrolibR.pdf

If a skyscapeR function has & behind its name then it has been transitioned for that function. In case of misc+, it is meant to relate to function eq2horFS (which is not needed when using swephR).

The following functions migth be embedded in swe_fixstar2_ut (missing though the color) and swe_calc_ut of swephR:
precess (misc+, stars&): 
	astrolibR::precess(ra[i], dec[i], 1950, j_now[i],fk4 = TRUE)
co_nutate (misc+, stars&): 
	astrolibR::co_nutate(jd, ra, dec)
co_aberration (misc+, stars&)
	tmp = astrolibR::co_aberration(jd, ra, dec, eps)
ct2lst (misc+)
	lmst = astrolibR::ct2lst(lon, 0, jd)
ten (stars&)
	astrolibR::ten(0,0,adj.pm[1])*sign(adj.pm[1])

Available in swephR:
jdcnv (mechanics&, data-entry&, stars&): swe_julday
juldate (misc&, stars&): swe_julday - 2400000
	astrolibR::juldate(c(year,1,1,12)) + 2400000 
	(due to adding the 2400000: this looks to be the normal jdcnv function)
co_refract (misc+): swe_refrac_extended
	alt = astrolibR::co_refract(alt, altitude = altitude, ..., to_observed = TRUE)
sunpos (mechanics&, misc&, stars&): swe_calc_ut(jd.t, 0, 2048)
hor2eq (data-entry&): swe_azalt_rev(2451545,1,c(hor$georef[,2],hor$georef[,1],0),c(az-180,alt))
	hor2eq(alt, az, jd, hor$georef[,1], hor$georef[,2], precess_ = F, ...)$dec, 
hadec2altaz (misc+) swe_azalt (2451545,1,c(0,lat,0),1013.25,15,c(ha,dec))
	tmp = astrolibR::hadec2altaz(ha, dec, lat, ws = ws)

REMEMBER azimuth in SE is from South towards West, while in skyscapeR azimuth is from North towards East.

```

**Comment by vreijs** [comment]
Relating to:
`hor2eq(alt, az, jd, hor$georef[,1], hor$georef[,2], precess_ = F, ...)$dec, `

Should that not be:

`hor2eq(alt, az, jd, hor$georef[,1], hor$georef[,2], nutate_=F,aberration_=F,precess_ = F, ...)$dec, `

I assume that nutate and aberration are included in the celestial object, so no need to also remove from them from horizon dec. (this is related to the reference coordinate system we use at a certain evaluation: aka geo/topo/app: http://archaeocosmology.org/eng/DecAltAziLat-environment.htm ). I want the horizon data to be independent of the date (so no nutate and aberration).

**Comment by vreijs** [comment]
It looks that I still need to use your stars.rda file, as swephR does not provide certain data as explicit output for:
. proper.motion
. it does not use HIP and HR as input, only MESSIER.ID, BAYER.DESIGNATION or NAME
. colour

Colour is important as that is related to e.g. your research on stars and passages (I have tested a way to include it in swephR, I prefer using B-V or Spectral Class)). 
How important are proper motion, HIP and HR?

**Comment by f-silva-archaeo** [comment]
Hi Victor

I don’t think we can remove proper motion from skyscapeR right now. It is needed for the declination calculation. We’ll remove it when we fully move to swephR.

I meant a fork, not a branch. That is the proper way to do it: you make your own fork, edit at will and then submit a merge with the main repository.


—

Fabio Silva, PhD

Research Associate, UCL Institute of Archaeology

Tutor, Sophia Centre for the Study of Cosmology in Culture, University of Wales Trinity Saint David

Secretary, European Society for Astronomy in Culture (SEAC)

Co-Founder and Co-Editor, Journal of Skyscape Archaeology<http://equinoxpub.com/JSA> (JSA)

Website/Blog: skyscaper.net<http://www.skyscaper.net>.  Twitter: @fsilva_archaeo<https://twitter.com/fsilva_archaeo>

On 23 Sep 2018, 4:22 PM +0200, Victor Reijs <notifications@github.com>, wrote:
Thanks for the feedback. At moment I decided to use your skyscapeR's color
function (and not change the SE functions [although I proposed a C code
change in SE, the SE authors are not that in favor at this moment, looking
at sustainability]). I though will keep pushing to get the Bmag (and
perhaps the spectral class) into SE.
Shall we remove from skyscapeR the proper motion from the output (and
perhaps also the HIP/HR search code), just to slowly migrate to the final
definition? Let me know.

By the way, I am not able to make branch in your skyscapeR, that is why I
made a fork (which is quite independent and perhaps not that handy). So can
you make a branch that I am allowed to make changes to?

All the best,

Victor

**Comment by vreijs** [comment]
On 23 September 2018 at 15:43, Fabio Silva <notifications@github.com> wrote:

> I don’t think we can remove proper motion from skyscapeR right now. It is
> needed for the declination calculation. We’ll remove it when we fully move
> to swephR.
>

In my fork I will do this removal though, see how it works and then we can
see (my fork with allow to go back to the original skyskapeR [except for
some obvious errors I mentioned, like the 2400000 and the jd hour error).


> I meant a fork, not a branch. That is the proper way to do it: you make
> your own fork, edit at will and then submit a merge with the main
> repository.
>

No problem; with Ralf I use branches, but forks also work;-)

All the best,


Victor

**Comment by vreijs** [comment]
Can you acknowledge these change:
```
jd <- astrolibR::jdcnv(2000, 1, 1, 0.)  # J2000.0
This should be: jdcnv(2000, 1, 1, 12.) as J2000.0 = 2451545
```
and
```
astrolibR::juldate(c(year,1,1,12)) + 2400000 
juldate is reduced Julian date number , so should the 2400000 not be 2440000?
```
The above are used in several R files and I just want to be sure that I am understand your code correctly.

**Comment by vreijs** [comment]
I think I now have replaced astrolib functions with swephR functions, but need to check if it all works oke when using vectors. So give me some more time to work on that.

I did not tackled yet the inconsistent use of geodec and topodec in the same graph, but that is related to skyscapeR functions, which I did not check yet (except for the reduced JDN and the J2000.0 definition). 

Again I keep making the changes in my fork: https://github.com/vreijs/skyscapeR

**Comment by vreijs** [comment]
By the way, I check swephR results with SkyMap Pro 12 than Stellarium. Stellarium has some problems, but its authors did not yet pick up my feedback related to star positions. I might try to debug Stellarium further when swephR and skyacape is 'done'.
