### ISSUE TITLE
eq.to.hor

### ISSUE THREAD

**Issue by vreijs** [f-silva-archaeo/skyscapeR#5]
In stars.R there are two references to eq.to.hor, but this is not defined (as a value). 
```
Sun.alt <- parallel::parApply(cl, X, 1, eq.to.Hor, lat=lat, lon=lon)
...
Star.alt <- parallel::parApply(cl, X, 1, eq.to.Hor, lat=lat, lon=lon)
```

There is a function eq.to.hor, but in the above code there are no arguments ... Cna you help me to understand what is needed?

**Comment by f-silva-archaeo** [comment]
Hi Victor

parApply takes a function, in this case eq.to.Hor, and applies it to all elements of X using parallelisation.

So yes in this case it is calling function eq.to.Hor()


—

Fabio Silva, PhD

Research Associate, UCL Institute of Archaeology

Tutor, Sophia Centre for the Study of Cosmology in Culture, University of Wales Trinity Saint David

Secretary, European Society for Astronomy in Culture (SEAC)

Co-Founder and Co-Editor, Journal of Skyscape Archaeology<http://equinoxpub.com/JSA> (JSA)

Website/Blog: skyscaper.net<http://www.skyscaper.net>.  Twitter: @fsilva_archaeo<https://twitter.com/fsilva_archaeo>

On 26 Sep 2018, 12:43 AM +0200, Victor Reijs <notifications@github.com>, wrote:

In stars.R there are two references to eq.to.hor, but this is not defined (as a value).

Sun.alt <- parallel::parApply(cl, X, 1, eq.to.Hor, lat=lat, lon=lon)
...
Star.alt <- parallel::parApply(cl, X, 1, eq.to.Hor, lat=lat, lon=lon)


There is a function eq.to.hor, but in the above code there are no arguments ... Cna you help me to understand what is needed?

**Comment by vreijs** [comment]
On 26 September 2018 at 07:49, Fabio Silva <notifications@github.com> wrote:

>
> parApply takes a function, in this case eq.to.Hor, and applies it to all
> elements of X using parallelisation.
>
> So yes in this case it is calling function eq.to.Hor()
>

Still have to get used to the interpreter languages, I did not 'source'
that R-file and then R can't find it;-) But now I get another error
(eq2horFS not found, while I can call it myself!) so I must have something
wrong in my code (I don't get that error using your R code). So working on
it;-).

By the way about the color. I found an error in the SIMBAD search engine
(they now repaired that), but I also asked them which of the two: 'B-V'
(Color Index) or Spectral Class is best to use as proxy to naked eye color
experience on Earth. No answer yer, but do you have an answer to that
question?
For me it is important in determining what I need to ask from SE-authors.

All the best,


Victor

**Comment by vreijs** [comment]
I have indeed that CSIRO link, I also asked them the same question (beside
the SIMBAD people). I personalty also though about the 'B-V' (as V means
visual;-), but just to be sure... Will inform you what the experts will say.

All the best,


Victor
