### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by gzotti** [f-silva-archaeo/skyscapeR#6]
Hi!

Just reading your "vignette" I came across a popular typo.

    Achronycal Setting "March 8 - March 30"

should be

    Acronycal Setting "March 8 - March 30"

The meaning is "edge of night", not "untimely" or such.

**Comment by vreijs** [comment]
I think this is B. Brady's definition, which I also find weird, but I think she has a reasoning around it....

**Comment by f-silva-archaeo** [comment]
It is Brady’s definition I use, but indeed there is a typo :)

Thanks for spotting it Georg!


----

Fabio Silva, PhD

Postdoctoral Researcher in Archaeology, Bournemouth University
Tutor, Sophia Centre for the Study of Cosmology in Culture, University of Wales Trinity Saint David
Secretary, European Society for Astronomy in Culture (SEAC)
Co-Founder and Co-Editor, Journal of Skyscape Archaeology (JSA)
Website/Blog: skyscaper.net<http://www.skyscaper.net>  Twitter: @fsilva_archaeo<https://twitter.com/fsilva_archaeo>

On 21 Dec 2018, 3:16 PM +0000, Victor Reijs <notifications@github.com>, wrote:

I think this is B. Brady's definition, which I also find weird, but I think she has a reasoning around it....
